### ISSUE TITLE
Issue on drawing more than 1 person

### ISSUE THREAD

**Issue by llanasnas** [over-engineer/Socket.io-whiteboard#4]
When 2 guys are drawing, a line is drawn between the clicks of each user, and the simple click is not functional.

**Comment by over-engineer** [comment]
Hey @llanasnas,

you’re absolutely right, thanks for reporting this! 😄

The drawing game this was initially developed for is no longer in active development, that’s why there might be some issues here and there that go unnoticed.

Both of the issues you mentioned have been fixed (the [demo](https://socketio-whiteboard.herokuapp.com/) has been updated with the new version as well).

- Multiple clients can now draw simultaneously without any weird lines connecting their paths
- Single clicks are now registered

Please keep in mind that both the frontend code (`lib/whiteboard.js`) **and** the backend code (`demo/server.js`) have to be updated.

**Comment by llanasnas** [comment]
Hello @over-engineer,

Good job with this issue, but now, if you change the color, when you draw something, all the lines drawed change his colour, and it's impossible to erase all content. check it if you want, this is only a comment.

Thaanks!

**Comment by over-engineer** [comment]
Hey @llanasnas,

>now, if you change the color, when you draw something, all the lines drawed change his colour

The issue where a color and/or thickness change affecting all clients (and what they’ve already drawn) is now fixed.

>it's impossible to erase all content

You can now call `whiteboard.clear()` to clear the entire canvas.

Also, I might look into some performance optimizations in the future. For the time being, though, its performance is “alright” for a small number of clients.
